import { ComponentFixture, TestBed } from '@angular/core/testing';
import { ClaimsTabComponent } from './claims-tab.component';
import { HttpClientTestingModule } from '@angular/common/http/testing';
import { ClaimService } from './claim.service';
import { StakeService } from '../../../core/services/stake.service';
import { Claim } from '../../../core/models/claim.model';
import { PendingTxStore } from '../../../core/services/pending-tx.service';
import { NotificationService } from '../../../core/services/notification.service';

describe('ClaimsTabComponent', () => {
  let component: ClaimsTabComponent;
  let fixture: ComponentFixture<ClaimsTabComponent>;
  let claimService: jasmine.SpyObj<ClaimService>;

  const mockClaims: Claim[] = [
    {
      id: 'claim-1',
      market_id: 'm-1',
      market_title: 'Will BTC hit 100k?',
      amount: 100,
      claimed: false,
      can_claim: true,
      market_state: 'RESOLVED',
      impact_generated_by_user: 50
    }
  ];

  beforeEach(async () => {
    const claimSpy = jasmine.createSpyObj('ClaimService', ['getClaims', 'executeClaim']);
    const stakeSpy = jasmine.createSpyObj('StakeService', ['placeStake']);
    const notificationSpy = jasmine.createSpyObj('NotificationService', ['show', 'update']);

    claimSpy.getClaims.and.returnValue(Promise.resolve(mockClaims));

    await TestBed.configureTestingModule({
      imports: [ClaimsTabComponent, HttpClientTestingModule],
      providers: [
        { provide: ClaimService, useValue: claimSpy },
        { provide: StakeService, useValue: stakeSpy },
        { provide: NotificationService, useValue: notificationSpy },
        PendingTxStore
      ]
    }).compileComponents();

    fixture = TestBed.createComponent(ClaimsTabComponent);
    component = fixture.componentInstance;
    claimService = TestBed.inject(ClaimService) as jasmine.SpyObj<ClaimService>;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  it('should display claims from the service', async () => {
    await fixture.whenStable();
    fixture.detectChanges();
    
    const compiled = fixture.nativeElement as HTMLElement;
    const claimTitle = compiled.querySelector('.market-title')?.textContent;
    expect(claimTitle).toContain('Will BTC hit 100k?');
    expect(claimService.getClaims).toHaveBeenCalled();
  });

  it('should show impact generated by user if exists', async () => {
    await fixture.whenStable();
    fixture.detectChanges();
    
    const compiled = fixture.nativeElement as HTMLElement;
    const impactBadge = compiled.querySelector('.impact-badge')?.textContent;
    expect(impactBadge).toContain('+50 XP');
  });
});
